allowBuilds:
  esbuild: true
  unrs-resolver: false
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days, See https://pnpm.io/settings#trustpolicyignoreafter
